version: '2'

services:
  postgres:
    container_name: postgres
    image: postgres:9.6.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=railsapp
      - POSTGRES_PASSWORD=railsapp
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - rubyapp_net

  redis:
    container_name: redis
    image: redis:4.0.1-alpine
    restart: always
#    command: redis-server --requirepass yourpassword
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:5.5.2-alpine
    restart: always
#    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  app:
    container_name: app
    build: .
    image: sfoxdev/ruby
    restart: always
#    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    env_file:
      - .env
    networks:
      - rubyapp_net

volumes:
  db-data:
  redis-data:
  elasticsearch-data:

networks:
  rubyapp_net:
    driver: bridge
