default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: railsapp
  password: railsapp
  pool: 5

development:
  <<: *default
  database: simple_payments_development

test:
  <<: *default
  database: simple_payments_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host:     <%= ENV['DB_HOST'] %>
  pool:     <%= ENV['DB_POOL'] %>
