# frozen_string_literal: true
source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '5.1.1'

# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'

# Application Server
gem 'puma', '3.2.0'

# Use Sass for stylesheets
gem 'sass-rails', '~> 5.0'
gem 'bootstrap-sass', '~> 3.3.7'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails', '~> 4.0'
# Use lodash as the JavaScript utility library similar to Ruby Enumerable module
gem 'lodash-rails', '~> 4.17'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5.0'

# CoffeeScript adapter for the Rails asset pipeline
gem 'coffee-rails', '~> 4.2'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '2.6.4'

# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Handles money transactions
gem 'money-rails', '~> 1.8'

# Convience gem for require file trees
gem 'require_all', '~> 1.3'

# For html requests
gem 'httparty', '~> 0.13'

# For template rendering
gem 'slim', '~> 3.0'

# For calculating schedules
gem 'business_time', '~> 0.9'
gem 'holidays', '~> 2.0'

# pagination
gem 'kaminari', '~> 0.17'

# decorators
gem 'draper', '~> 3.0'

# font awesome icons
gem 'font-awesome-rails', '~> 4.5'

# For background jobs
gem 'sidekiq', '~> 4'
gem 'sidekiq-monitor-stats', '~> 0.0.1'
gem 'sinatra', '~> 2.0', :require => nil

# For error handling
gem 'rollbar'

# Suggested by rollbar for JSON serialization
gem 'oj', '~> 2.12.14'

# date picker bootstrap style
gem 'bootstrap-datepicker-rails', '~> 1.6'

# date library for js
gem 'momentjs-rails', '~> 2.17'

# Sales tax service
gem 'avatax', '~> 14.4'

# For date parsing
gem 'chronic', '~> 0.10'

# encryption
gem 'attr_encrypted', '~> 3.0'

# For asynchronous, distributed communication between services
gem 'concurrent-ruby', '~> 1.0'
gem 'concurrent-ruby-ext', '1.0.0.pre3'
gem 'redlock', '~> 0.2.0'

# Framework for service objects
gem 'aldous', '~> 1.1'

# Handles Roles
gem 'rolify', '~> 5.1'

# generates crontab for scheduling jobs
gem 'whenever', '~> 0.9', :require => false

# view helper to manage "active" state of a link
gem 'active_link_to', '~> 1.0'

# provides correct geographical names for countries/states
gem 'carmen', '~> 1.0'

# used for attaching documents
gem 'paperclip', '5.0.0'

# for file saving to S3
gem 'aws-sdk', '~> 2.0'

# monitoring and local debugging
gem 'newrelic_rpm', '~> 3.18'

# For handling environment variables
gem 'dotenv-rails', '~> 2.1'

# influxdb library
gem 'influxdb', '~> 0.3', require: false

# For logging outgoing request
gem 'http_logger', '~> 0.5'
gem 'elasticsearch', '~> 5.0'

# Makes printing data in console awesome! (usage: ap object)
gem 'awesome_print', '~> 1.7'

# Services API
gem 'grape', '~> 0.19.1'
gem 'grape-entity', '~> 0.6.0'
gem 'grape-swagger', '~> 0.26.1'
gem 'grape-swagger-entity', '~> 0.1.6'
gem 'grape-swagger-representable', '~> 0.1.3'

# Allows for simple and flexibile attribute definition for service objects
gem 'virtus', '~> 1.0'

# For iterating dates and building schedules
gem 'ice_cube', '~> 0.16'

# For long running rake tasks
gem 'ruby-progressbar', '~> 1.8'

# For XML serialization
gem 'activemodel-serializers-xml', '~> 1.0'

group :development do
  # better errors gives you a console in the browser, the error page looks better too
  gem 'better_errors', '~> 2.1'

  # Linting
  gem 'rubocop', '~> 0.47', require: false

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 3.1.0'

  # For deployment
  gem 'capistrano-rails', '~> 1.1'

  # in app style guide
  gem 'hologram', '~> 1.4'
  gem 'guard-hologram', '~> 1.0'

  # Used to identify N+1 queries
  gem 'bullet', '~> 5.5'

  # Used to identify security risks
  gem 'brakeman', require: false

  # Services endpoint documentation
  gem 'grape-swagger-rails', '~> 0.3.0'

  # Annotate Rails classes with schema and routes info
  gem 'annotate', '~> 2.7.1'
end

group :development, :test, :training, :st do
  # Readline support
  gem 'rb-readline', '~> 0.5'

  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', '~> 4.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring', '~> 1.3'

  # Testing factories
  gem 'factory_girl_rails', '~> 4.8'

  # faker gem to create fake data
  gem 'faker', ' ~> 1.7'

  # For testing JS
  gem 'jasmine-rails', '~> 0.14.1'
end

group :qa do
  # Testing factories
  gem 'factory_girl_rails', '~> 4.8'

  # faker gem to create fake data
  gem 'faker', ' ~> 1.7'
end

group :development, :test do
  # For debugging
  gem 'pry', '~> 0.10'

  gem 'pry-rails', '~> 0.3'

  gem 'pry-byebug', '~> 3.1'

  # For manipulating time in tests, benchmarking, and data population
  gem 'timecop', '~> 0.8'

  # Enhance your hash
  gem 'hashie', '~> 3.5'
end

group :test do
  # allows to automatically & intelligently launch specs when files are modified
  gem 'guard-rspec', '~> 4.7', require: false
  gem 'rspec-sidekiq', '~> 3.0'

  gem 'kaminari-rspec', '~> 0.16'

  # Testing library
  gem 'rspec-rails', '~> 3.6'

  # For integration testing
  gem 'capybara', '~> 2.4'
  # For testing JS with Capybara
  gem 'poltergeist', '~> 1.6'

  # Removes DB records after running specs
  gem 'database_cleaner', '~> 1.6'

  # Stubs out external systems
  gem 'vcr', '~> 2.9'

  gem 'webmock', '~> 1.21'

  # Brings back the `assigns` to controller tests in Rails 5
  gem 'rails-controller-testing', '~> 1.0'

  gem 'simplecov', require: false
end
